### Joshua Kyle K. Entrata

### 4CSC - Data Analysis and Visualization


In [1]:
import numpy as np
import pandas as pd

### Part 1: Introduction to NumPy


#### Task 1: Creating Arrays

Create a 1D NumPy array containing the numbers from 1 to 15.


In [2]:
"""
I generated a sequence of numbers starting from 1 to 15 and converted it into a NumPy array

Another option is to manually set the list [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
"""

arr = np.array([x for x in range(1,16)])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


#### Task 2: Reshaping Arrays

Reshape the 1D array from Task 1 into a 3x5 2D array.


In [3]:
"""
We can reshape a NumPy array using the `reshape()` method by passing a valid dimensions that match the total number of elements in that array
"""

new_arr = arr.reshape(3, 5)
print(new_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


#### Task 3: Basic Arithmetic Operations

Create a new array by adding 2 to every element in the 2D array from Task 2


In [4]:
"""
Directly applying arithmetic operations, such as addition, is allowed on a NumPy array
"""
add_arr = new_arr + 2
print(add_arr)

[[ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]]


#### Task 4: Array Indexing and Slicing

Extract the second row from the 2D array you created in Task 2.


In [6]:
"""
Using indexing, we can extract specific rows from a NumPy array 

For this instance, since indexing starts at 0, index 1 refers to the second row
"""
extracted_arr = new_arr[1]
print(extracted_arr)

[ 6  7  8  9 10]


#### Task 5: Element-wise Operations

Multiply each element in the 2D array by 3 and store the result in a new array.


In [7]:
"""
Same with arithmetic operations, we can perform elemnent-wise multiplication on a NumPy array
"""

mul_arr = new_arr * 3
print(mul_arr)

[[ 3  6  9 12 15]
 [18 21 24 27 30]
 [33 36 39 42 45]]


#### Task 6: Basic Statistics

Calculate the mean and sum of all elements in the array from Task 5.


In [8]:
"""
NumPy has functions such as `mean()` and `sum()` that we can use to calculate the mean and sum of all elements in the array
"""

mean_of_arr = np.mean(mul_arr)
sum_of_arr = np.sum(mul_arr)

print(f'Mean of all elements in the array is {mean_of_arr}.')
print(f'Sum of all elements in the array is {sum_of_arr}.')

Mean of all elements in the array is 24.0.
Sum of all elements in the array is 360.


### Part 2: Introduction to Pandas


#### Task 7: Creating DataFrames

Create a Pandas DataFrame using the followind data:


In [9]:
"""
We can create a DataFrame in Pandas by passing a dictionary
"""

data = {
    'Name': ['Tom', 'Jane', 'Steve'],
    'Age': [28, 34, 29],
    'Salary': [50000, 60000, 55000]
}

df = pd.DataFrame(data)
print(df)

    Name  Age  Salary
0    Tom   28   50000
1   Jane   34   60000
2  Steve   29   55000


#### Task 8: Accessing DataFrame Columns

Select the 'Name' column from the DataFrame and display it.


In [10]:
"""
We can access a specific column by using the column name as a key
"""

print(df['Name'])

0      Tom
1     Jane
2    Steve
Name: Name, dtype: object


#### Task 9: Adding a New Column

Add a new column to the DataFrame called 'Bonus', which is 10% of the 'Salary'


In [11]:
"""
We can create a new column by creating a new column name

For its values, we can perform operations on existing columns and assigning it to the new column
"""

df['Bonus'] = df['Salary'] * 0.1
print(df)

    Name  Age  Salary   Bonus
0    Tom   28   50000  5000.0
1   Jane   34   60000  6000.0
2  Steve   29   55000  5500.0


#### Task 10: Basic DataFrame Statistics

Calculate the average salary of all individuals in the DataFrame


In [12]:
"""
We can use the `mean()` method to calculate the average of the `Salary` column
"""

ave_salary = df['Salary'].mean()
print(f'The average salary of all individuals is {ave_salary}')

The average salary of all individuals is 55000.0
